import type { ClassRecord } from '@/app/lib/game-hub/types';

// Brown Dust 2 unit roster. In BD2 the pullable unit is a costume, so each
// entry is a costume with its own rarity/role/element and PvE (Story) / PvP
// (Mirror War) tier. Fields are omitted when the source lists no value; every
// unit carries at least one source (cite-or-drop).
export const CHARACTERS: ClassRecord[] = [
  {
    slug: 'apostle-morpeah',
    name: 'Apostle Morpeah',
    role: 'Attacker (DPS)',
    rarity: '5★',
    element: 'Water',
    pveTier: 'S',
    bossTier: 'S',
    guildTier: 'A',
    sources: [
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://dotgg.gg/brown-dust-2/pve-tier-list/',
      'https://www.propelrc.com/ultimate-brown-dust-2-tier-list/',
    ],
  },
  {
    slug: 'apostle-blade',
    name: 'Apostle Blade',
    role: 'Attacker (Counterattack DPS)',
    rarity: '5★',
    element: 'Dark',
    pveTier: 'S',
    bossTier: 'S',
    guildTier: 'S',
    sources: [
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
      'https://www.pockettactics.com/brown-dust-2/tier-list',
    ],
  },
  {
    slug: 'deadeye-nekyndalia',
    name: 'Deadeye Nekyndalia',
    role: 'Attacker (Single-target Sniper)',
    rarity: '5★',
    element: 'Wind',
    pveTier: 'S',
    sources: [
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
      'https://www.pockettactics.com/brown-dust-2/tier-list',
    ],
  },
  {
    slug: 'nebris',
    name: 'Nebris',
    role: 'Attacker (Single-target burst)',
    rarity: '5★',
    element: 'Wind',
    pveTier: 'S',
    bossTier: 'A',
    guildTier: 'A',
    sources: [
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://dotgg.gg/brown-dust-2/pve-tier-list/',
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
    ],
  },
  {
    slug: 'bikini-agent-sylvia',
    name: 'Bikini Agent Sylvia',
    role: 'Attacker (DPS)',
    rarity: '5★',
    element: 'Water',
    pveTier: 'S',
    bossTier: 'S',
    guildTier: 'S',
    sources: [
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://dotgg.gg/brown-dust-2/pve-tier-list/',
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
    ],
  },
  {
    slug: 'naive-lady-elise',
    name: 'Naive Lady Elise',
    role: 'Attacker (DPS Carry)',
    rarity: '5★',
    element: 'Fire',
    pveTier: 'S',
    sources: ['https://www.pocketgamer.com/brown-dust-2/tier-list/'],
  },
  {
    slug: 'violent-student-kry',
    name: 'Violent Student Kry',
    role: 'Attacker (F2P-friendly DPS)',
    rarity: '5★',
    element: 'Dark',
    pveTier: 'S',
    sources: [
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
      'https://www.pockettactics.com/brown-dust-2/tier-list',
    ],
  },
  {
    slug: 'young-lady-blade',
    name: 'Young Lady Blade',
    role: 'Attacker (AoE burst)',
    rarity: '5★',
    pveTier: 'S',
    pvpTier: 'S',
    sources: [
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://dotgg.gg/brown-dust-2/pvp-tier-list/',
    ],
  },
  {
    slug: 'venaka',
    name: 'Venaka',
    rarity: '5★',
    pveTier: 'S',
    bossTier: 'A',
    guildTier: 'A',
    sources: [
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://vortexgaming.io/en/postdetail/616661',
    ],
  },
  {
    slug: 'liatris',
    name: 'Liatris',
    rarity: '5★',
    element: 'Fire',
    pveTier: 'S',
    sources: ['https://www.pockettactics.com/brown-dust-2/tier-list'],
  },
  {
    slug: 'levia',
    name: 'Levia',
    rarity: '5★',
    pveTier: 'S',
    bossTier: 'A',
    guildTier: 'A',
    sources: [
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://vortexgaming.io/en/postdetail/616661',
    ],
  },
  {
    slug: 'loen',
    name: 'Loen',
    rarity: '5★',
    pveTier: 'S',
    sources: ['https://www.pockettactics.com/brown-dust-2/tier-list'],
  },
  {
    slug: 'yuri',
    name: 'Yuri',
    rarity: '5★',
    pveTier: 'S',
    sources: ['https://www.pockettactics.com/brown-dust-2/tier-list'],
  },
  {
    slug: 'samay',
    name: 'Samay',
    rarity: '5★',
    element: 'Dark',
    pveTier: 'S',
    sources: ['https://www.pockettactics.com/brown-dust-2/tier-list'],
  },
  {
    slug: 'sentana',
    name: 'Sentana',
    rarity: '5★',
    pveTier: 'S',
    sources: ['https://www.pockettactics.com/brown-dust-2/tier-list'],
  },
  {
    slug: 'eclipse',
    name: 'Eclipse',
    rarity: '5★',
    pveTier: 'S',
    sources: ['https://www.pockettactics.com/brown-dust-2/tier-list'],
  },
  {
    slug: 'luvencia',
    name: 'Luvencia',
    rarity: '5★',
    pveTier: 'S',
    bossTier: 'A',
    guildTier: 'A',
    sources: [
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://vortexgaming.io/en/postdetail/616661',
    ],
  },
  {
    slug: 'beachside-angel-teresse',
    name: 'Beachside Angel Teresse',
    rarity: '5★',
    pveTier: 'S',
    sources: ['https://www.pockettactics.com/brown-dust-2/tier-list'],
  },
  {
    slug: 'beachside-justice-michaela',
    name: 'Beachside Justice Michaela',
    rarity: '5★',
    pveTier: 'S',
    sources: ['https://www.pockettactics.com/brown-dust-2/tier-list'],
  },
  {
    slug: 'magical-innovator-diana',
    name: 'Magical Innovator Diana',
    role: 'Supporter (Elemental Buffer)',
    rarity: '5★',
    element: 'Wind',
    pveTier: 'S',
    sources: [
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
      'https://www.pockettactics.com/brown-dust-2/tier-list',
    ],
  },
  {
    slug: 'pure-white-blessing-refithea',
    name: 'Pure White Blessing Refithea',
    role: 'Supporter (Buffer, crit/attack buffs)',
    rarity: '5★',
    element: 'Light',
    pveTier: 'S',
    sources: [
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
      'https://dotgg.gg/brown-dust-2/pve-tier-list/',
    ],
  },
  {
    slug: 'earth-mother-believer-priestess',
    name: 'Earth Mother Believer Priestess',
    role: 'Supporter (Healer)',
    rarity: '5★',
    element: 'Light',
    pveTier: 'S',
    sources: [
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
      'https://www.pockettactics.com/brown-dust-2/tier-list',
    ],
  },
  {
    slug: 'palette-shattered-dream',
    name: 'Palette (Shattered Dream)',
    role: 'Supporter (Debuff Extender)',
    rarity: '5★',
    element: 'Dark',
    pveTier: 'S',
    bossTier: 'S',
    guildTier: 'S',
    sources: ['https://www.pocketgamer.com/brown-dust-2/tier-list/'],
  },
  {
    slug: 'shadowed-dream-sonya',
    name: 'Shadowed Dream Sonya',
    role: 'Supporter (Debuffer / damage amp)',
    rarity: '5★',
    element: 'Dark',
    pveTier: 'S',
    pvpTier: 'S',
    bossTier: 'A',
    guildTier: 'A',
    sources: [
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://dotgg.gg/brown-dust-2/pvp-tier-list/',
      'https://vortexgaming.io/en/postdetail/616661',
    ],
  },
  {
    slug: 'dark-saintess-liberta',
    name: 'Dark Saintess Liberta',
    role: 'Supporter (physical-team support)',
    rarity: '5★',
    pveTier: 'S',
    sources: [
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://dotgg.gg/brown-dust-2/pve-tier-list/',
    ],
  },
  {
    slug: 'acting-archbishop-michaela',
    name: 'Acting Archbishop Michaela',
    role: 'Supporter (Debuffer)',
    rarity: '5★',
    pveTier: 'S',
    pvpTier: 'S',
    bossTier: 'S',
    sources: [
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://dotgg.gg/brown-dust-2/pvp-tier-list/',
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
    ],
  },
  {
    slug: 'b-rank-helena',
    name: 'B-Rank Helena',
    role: 'Supporter (magic-team support)',
    rarity: '4★',
    pveTier: 'A',
    sources: [
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://dotgg.gg/brown-dust-2/pve-tier-list/',
    ],
  },
  {
    slug: 'empress-rubia',
    name: 'Empress Rubia',
    role: 'Attacker (DPS)',
    rarity: '5★',
    pveTier: 'A',
    pvpTier: 'S',
    sources: [
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://dotgg.gg/brown-dust-2/pvp-tier-list/',
    ],
  },
  {
    slug: 'pool-party-justia',
    name: 'Pool Party Justia',
    role: 'Defender (evasion tank)',
    rarity: '5★',
    element: 'Light',
    pvpTier: 'S',
    sources: ['https://dotgg.gg/brown-dust-2/pvp-tier-list/'],
  },
  {
    slug: 'apostle-olivier',
    name: 'Apostle Olivier',
    role: 'Defender (evasion tank)',
    rarity: '5★',
    pvpTier: 'S',
    sources: ['https://dotgg.gg/brown-dust-2/pvp-tier-list/'],
  },
  {
    slug: 'dark-knight-lathel',
    name: 'Dark Knight Lathel',
    role: 'Defender (guard / damage reduction)',
    rarity: '5★',
    pvpTier: 'S',
    sources: ['https://dotgg.gg/brown-dust-2/pvp-tier-list/'],
  },
  {
    slug: 'iron-monarch-wilhelmina',
    name: 'Iron Monarch Wilhelmina',
    role: 'Attacker (pre-battle Earth damage)',
    rarity: '5★',
    element: 'Earth',
    pveTier: 'A',
    pvpTier: 'S',
    bossTier: 'A',
    guildTier: 'S',
    sources: [
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
      'https://dotgg.gg/brown-dust-2/pvp-tier-list/',
      'https://vortexgaming.io/en/postdetail/616661',
    ],
  },
  {
    slug: 'ocean-vanguard-luvencia',
    name: 'Ocean Vanguard Luvencia',
    rarity: '5★',
    pveTier: 'A',
    sources: ['https://www.pocketgamer.com/brown-dust-2/tier-list/'],
  },
  {
    slug: 'deserted-flower-sylvia',
    name: 'Deserted Flower Sylvia',
    role: 'Attacker (Water DPS)',
    rarity: '5★',
    element: 'Water',
    pveTier: 'A',
    sources: ['https://www.pocketgamer.com/brown-dust-2/tier-list/'],
  },
  {
    slug: 'onsen-practitioner-ventana',
    name: 'Onsen Practitioner Ventana',
    rarity: '5★',
    pveTier: 'A',
    bossTier: 'A',
    sources: [
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
      'https://www.pockettactics.com/brown-dust-2/tier-list',
    ],
  },
  {
    slug: 'wiggle',
    name: 'Wiggle',
    rarity: '5★',
    pveTier: 'A',
    sources: [
      'https://www.pocketgamer.com/brown-dust-2/tier-list/',
      'https://www.pockettactics.com/brown-dust-2/tier-list',
    ],
  },
  {
    slug: 'scheherazade',
    name: 'Scheherazade (Schera)',
    rarity: '5★',
    pveTier: 'A',
    bossTier: 'A',
    guildTier: 'A',
    sources: [
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://vortexgaming.io/en/postdetail/616661',
    ],
  },
  {
    slug: 'rafina',
    name: 'Rafina',
    rarity: '5★',
    pveTier: 'A',
    bossTier: 'A',
    guildTier: 'A',
    sources: [
      'https://www.pockettactics.com/brown-dust-2/tier-list',
      'https://vortexgaming.io/en/postdetail/616661',
    ],
  },
  {
    slug: 'rou',
    name: 'Rou',
    rarity: '5★',
    element: 'Dark',
    pveTier: 'A',
    sources: ['https://www.pockettactics.com/brown-dust-2/tier-list'],
  },
  {
    slug: 'darian',
    name: 'Darian',
    role: 'Attacker (sustained DoT DPS)',
    rarity: '5★',
    element: 'Fire',
    pveTier: 'S',
    bossTier: 'S',
    guildTier: 'S',
    sources: [
      'https://www.propelrc.com/ultimate-brown-dust-2-tier-list/',
      'https://dotgg.gg/brown-dust-2/pve-tier-list/',
      'https://vortexgaming.io/en/postdetail/616661',
    ],
  },
  {
    slug: 'mamonir',
    name: 'Mamonir (Mammonir of the Night of Death)',
    role: 'Attacker (magic DPS, crit / HP-scaling)',
    rarity: '5★',
    element: 'Wind',
    bossTier: 'A',
    guildTier: 'A',
    sources: [
      'https://www.propelrc.com/ultimate-brown-dust-2-tier-list/',
      'https://vortexgaming.io/en/postdetail/616661',
    ],
  },
  {
    slug: 'tyr',
    name: 'Tyr',
    role: 'Attacker (dealer)',
    rarity: '5★',
    pveTier: 'S',
    bossTier: 'A',
    guildTier: 'A',
    sources: [
      'https://vortexgaming.io/en/postdetail/616661',
      'https://dotgg.gg/brown-dust-2/pve-tier-list/',
    ],
  },
  {
    slug: 'celia',
    name: 'Celia',
    role: 'Attacker (raid chain dealer)',
    rarity: '5★',
    bossTier: 'A',
    guildTier: 'A',
    sources: [
      'https://vortexgaming.io/en/postdetail/616661',
      'https://dotgg.gg/brown-dust-2/pve-tier-list/',
    ],
  },
  {
    slug: 'zenith',
    name: 'Zenith',
    role: 'Attacker (raid chain dealer)',
    rarity: '5★',
    bossTier: 'A',
    guildTier: 'A',
    sources: ['https://vortexgaming.io/en/postdetail/616661'],
  },
  {
    slug: 'splash-queen-wilhelmina',
    name: 'Splash Queen Wilhelmina',
    role: 'Attacker (single-target boss DPS)',
    rarity: '5★',
    bossTier: 'S',
    sources: ['https://www.pocketgamer.com/brown-dust-2/tier-list/'],
  },
];
