// Custom worker entry: serves the OpenNext-built Next.js app and adds the
// cron handler that replaces the Vercel cron (vercel.json `crons`).
//
// The cron fires every 5 minutes (wrangler.jsonc `triggers.crons`) and calls
// the existing /api/cron/revalidate-recent route through the worker's
// self-reference binding, authenticated the same way Vercel Cron was:
// `Authorization: Bearer $CRON_SECRET`.

// @ts-expect-error generated by `opennextjs-cloudflare build`
import handler from './.open-next/worker.js';

export default {
  // www → apex 301. Done here (not next.config redirects) because OpenNext's
  // cache interception can serve a cached page before Next's host-based
  // redirect rules are evaluated.
  fetch(request: Request, env: unknown, ctx: unknown) {
    const url = new URL(request.url);
    if (url.hostname === 'www.finalboss.io') {
      url.hostname = 'finalboss.io';
      return Response.redirect(url.toString(), 301);
    }
    return handler.fetch(request, env, ctx);
  },

  async scheduled(_controller, env, ctx) {
    ctx.waitUntil(
      env.WORKER_SELF_REFERENCE.fetch(
        'https://finalboss.io/api/cron/revalidate-recent',
        { headers: { authorization: `Bearer ${env.CRON_SECRET}` } },
      ),
    );
  },
} satisfies ExportedHandler<CloudflareEnv & { CRON_SECRET: string }>;

// Durable Object classes used by the OpenNext cache (queue + tag cache).
// @ts-expect-error generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js';
