import type { CodeRecord } from '@/app/lib/game-hub/types';

const PG = 'https://pocketgamer.com/crystal-of-atlan/codes';

export const CODES: { lastVerified: string; entries: CodeRecord[] } = {
  lastVerified: '2026-07-04',
  entries: [
    { code: 'COASaintOne', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAStoopzz', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COA39Daph', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COADslily', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COATectone', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COApayo', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COASoda0529', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAEmily0529', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COACYR0529', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAZentreya', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COABao', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COADeme', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAFuchsia', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAAlkaizerX', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COABen', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAYuzu', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAMataraKan', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAFEFE0529', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAAhmpy', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAMeerestv', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COASunglit', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COADinah', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAMonroe529', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COALuquEt4', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COASmzinho', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAmetashi', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAZeratoR', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAJltomy', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COATonton', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAREVENANT', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAPippa', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COAPayne', reward: "5 Hunting Permits (Bound), 2 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'COATOP1EN', reward: '10 Arcanite of Adore', status: 'active', sources: [PG] },
    { code: 'COATEAMUP528', reward: '10 Hunting Permits (Bound)', status: 'active', sources: [PG] },
    { code: 'COAcreator2', reward: "150k Bound Gold, 3 Maltz's Special Injections", status: 'active', sources: [PG] },
    { code: 'inventor', status: 'active', sources: [PG] },
    { code: 'CoAJodie', status: 'active', sources: [PG] },
    { code: 'CoAnewyear', status: 'active', sources: [PG] },
    { code: 'Yearof2026', status: 'active', sources: [PG] },
    { code: 'HappyXmas', status: 'active', sources: [PG] },
    { code: 'Snowbrush', status: 'active', sources: [PG] },
    { code: 'BrushSnow', status: 'active', sources: [PG] },
    { code: 'SnowyTime', status: 'active', sources: [PG] },
    { code: 'Hometown2', status: 'active', sources: [PG] },
    { code: 'Christmas2', status: 'active', sources: [PG] },
    { code: 'SemiYear', status: 'active', sources: [PG] },
    { code: 'aerstria', status: 'active', sources: [PG] },
    { code: 'NellanCoA', status: 'active', sources: [PG] },
    { code: 'shondarouBduckCoA', status: 'active', sources: [PG] },
    { code: 'Christmas1', status: 'active', sources: [PG] },
    { code: 'COAVT03', status: 'active', sources: [PG] },
    { code: 'COA03NO1', status: 'active', sources: [PG] },
    { code: 'COA03NO2', status: 'active', sources: [PG] },
    { code: 'COA03NO3', status: 'active', sources: [PG] },
    { code: 'CoASnow', status: 'active', sources: [PG] },
    { code: 'CoABduck', status: 'active', sources: [PG] },
    { code: 'inventor312', status: 'active', sources: [PG] },
    { code: 'CoAJodie312', status: 'active', sources: [PG] },
    { code: 'BduckCollab', status: 'active', sources: [PG] },
    { code: 'BduckHome', status: 'active', sources: [PG] },
    { code: 'COAcreator', status: 'active', sources: [PG] },
    { code: 'COASEACOMBO', status: 'active', sources: [PG] },
    { code: 'COA222', status: 'active', sources: [PG] },
    { code: 'COA777', status: 'active', sources: [PG] },
    { code: 'COA555', status: 'active', sources: [PG] },
    { code: 'COAJP527', status: 'active', sources: [PG] },
    { code: 'COAJP123', status: 'active', sources: [PG] },
    { code: 'COAJP888', status: 'active', sources: [PG] },
    { code: 'COATOP1AS', status: 'active', sources: [PG] },
    { code: 'COAwin1', status: 'active', sources: [PG] },
    { code: 'COAwin2', status: 'active', sources: [PG] },
    { code: 'COA100v', status: 'active', sources: [PG] },
    { code: 'COA1500', status: 'active', sources: [PG] },
    { code: 'JodieCOA', status: 'active', sources: [PG] },
    { code: 'CoAJodi', status: 'active', sources: [PG] },
    { code: 'BduckFun', status: 'active', sources: [PG] },
    { code: 'HomeBduck', status: 'active', sources: [PG] },
    { code: 'COATOP1PS', status: 'active', sources: [PG] },
  ],
};
