import type { ClassRecord } from '@/app/lib/game-hub/types';

// Zenless Zone Zero Agent roster. Attribute (element) and Specialty (role) come
// from the Icy Veins Agents database; the single tier (pveTier) is normalized
// from the Game8 3.0 tier list (July 2026): Tier 0 -> "S+", Tier 1+ -> "S",
// Tier 1 -> "A". ZZZ has no arena PvP — the tier reflects the endgame combat
// content (Shiyu Defense / Deadly Assault) those sources rank against. Fields
// are omitted when a source lists no value; every unit carries its sources.
const G8 = 'https://game8.co/games/Zenless-Zone-Zero/archives/435685';
const IV = 'https://www.icy-veins.com/zenless-zone-zero/agents';

export const CHARACTERS: ClassRecord[] = [
  // ---- Tier 0 (S+) ----
  {
    slug: 'hoshimi-miyabi',
    name: 'Hoshimi Miyabi',
    aliases: ['Miyabi'],
    role: 'Anomaly (Main DPS)',
    rarity: 'S-Rank',
    element: 'Frost',
    pveTier: 'S+',
    sources: [G8, IV],
  },
  {
    slug: 'astra-yao',
    name: 'Astra Yao',
    role: 'Support',
    rarity: 'S-Rank',
    element: 'Ether',
    pveTier: 'S+',
    sources: [G8, IV],
  },
  {
    slug: 'yixuan',
    name: 'Yixuan',
    role: 'Rupture (Main DPS)',
    rarity: 'S-Rank',
    element: 'Auric Ink',
    pveTier: 'S+',
    sources: [G8, IV],
  },
  {
    slug: 'ye-shunguang',
    name: 'Ye Shunguang',
    role: 'Attack (Main DPS)',
    rarity: 'S-Rank',
    element: 'Honed Edge',
    pveTier: 'S+',
    isNew: true,
    sources: [G8, IV],
  },
  {
    slug: 'ukinami-yuzuha',
    name: 'Ukinami Yuzuha',
    aliases: ['Yuzuha'],
    role: 'Support',
    rarity: 'S-Rank',
    element: 'Physical',
    pveTier: 'S+',
    sources: [G8, IV],
  },
  {
    slug: 'sunna',
    name: 'Sunna',
    role: 'Support',
    rarity: 'S-Rank',
    element: 'Physical',
    pveTier: 'S+',
    isNew: true,
    sources: [G8, IV],
  },
  {
    slug: 'lucia',
    name: 'Lucia',
    role: 'Support',
    rarity: 'S-Rank',
    element: 'Ether',
    pveTier: 'S+',
    sources: [G8, IV],
  },
  {
    slug: 'dialyn',
    name: 'Dialyn',
    role: 'Stun',
    rarity: 'S-Rank',
    element: 'Physical',
    pveTier: 'S+',
    sources: [G8, IV],
  },
  {
    slug: 'ju-fufu',
    name: 'Ju Fufu',
    role: 'Stun',
    rarity: 'S-Rank',
    element: 'Fire',
    pveTier: 'S+',
    sources: [G8, IV],
  },
  {
    slug: 'norma',
    name: 'Norma',
    role: 'Stun',
    rarity: 'S-Rank',
    element: 'Fire',
    pveTier: 'S+',
    isNew: true,
    sources: [G8, IV],
  },
  {
    slug: 'nangong-yu',
    name: 'Nangong Yu',
    role: 'Stun',
    rarity: 'S-Rank',
    element: 'Ether',
    pveTier: 'S+',
    sources: [G8, IV],
  },
  {
    slug: 'velina',
    name: 'Velina',
    role: 'Anomaly (Main DPS)',
    rarity: 'S-Rank',
    element: 'Wind',
    pveTier: 'S+',
    isNew: true,
    sources: [G8, IV],
  },
  {
    slug: 'trigger',
    name: 'Trigger',
    role: 'Stun',
    rarity: 'S-Rank',
    element: 'Electric',
    pveTier: 'S+',
    sources: [G8, IV],
  },
  // ---- Tier 1+ (S) ----
  {
    slug: 'evelyn-chevalier',
    name: 'Evelyn Chevalier',
    aliases: ['Evelyn'],
    role: 'Attack (Main DPS)',
    rarity: 'S-Rank',
    element: 'Fire',
    pveTier: 'S',
    sources: [G8, IV],
  },
  {
    slug: 'vivian',
    name: 'Vivian',
    role: 'Anomaly',
    rarity: 'S-Rank',
    element: 'Ether',
    pveTier: 'S',
    sources: [G8, IV],
  },
  {
    slug: 'soldier-0-anby',
    name: 'Soldier 0 - Anby',
    role: 'Attack (Main DPS)',
    rarity: 'S-Rank',
    element: 'Electric',
    pveTier: 'S',
    sources: [G8, IV],
  },
  {
    slug: 'tsukishiro-yanagi',
    name: 'Tsukishiro Yanagi',
    aliases: ['Yanagi'],
    role: 'Anomaly (Main DPS)',
    rarity: 'S-Rank',
    element: 'Electric',
    pveTier: 'S',
    sources: [G8, IV],
  },
  {
    slug: 'burnice-white',
    name: 'Burnice White',
    aliases: ['Burnice'],
    role: 'Anomaly (Sub-DPS)',
    rarity: 'S-Rank',
    element: 'Fire',
    pveTier: 'S',
    sources: [G8, IV],
  },
  {
    slug: 'lighter',
    name: 'Lighter',
    role: 'Stun',
    rarity: 'S-Rank',
    element: 'Fire',
    pveTier: 'S',
    sources: [G8, IV],
  },
  {
    slug: 'hugo-vlad',
    name: 'Hugo Vlad',
    aliases: ['Hugo'],
    role: 'Attack (Main DPS)',
    rarity: 'S-Rank',
    element: 'Ice',
    pveTier: 'S',
    sources: [G8, IV],
  },
  {
    slug: 'alice-thymefield',
    name: 'Alice Thymefield',
    aliases: ['Alice'],
    role: 'Anomaly (Main DPS)',
    rarity: 'S-Rank',
    element: 'Physical',
    pveTier: 'S',
    sources: [G8, IV],
  },
  {
    slug: 'aria',
    name: 'Aria',
    role: 'Anomaly',
    rarity: 'S-Rank',
    element: 'Ether',
    pveTier: 'S',
    sources: [G8, IV],
  },
  {
    slug: 'zhao',
    name: 'Zhao',
    role: 'Defense',
    rarity: 'S-Rank',
    element: 'Ice',
    pveTier: 'S',
    sources: [G8, IV],
  },
  // ---- Tier 1 (A) — strong older S-Rank units ----
  {
    slug: 'jane-doe',
    name: 'Jane Doe',
    aliases: ['Jane'],
    role: 'Anomaly (Main DPS)',
    rarity: 'S-Rank',
    element: 'Physical',
    pveTier: 'A',
    sources: [G8, IV],
  },
  {
    slug: 'ellen-joe',
    name: 'Ellen Joe',
    aliases: ['Ellen'],
    role: 'Attack (Main DPS)',
    rarity: 'S-Rank',
    element: 'Ice',
    pveTier: 'A',
    sources: [G8, IV],
  },
  {
    slug: 'qingyi',
    name: 'Qingyi',
    role: 'Stun',
    rarity: 'S-Rank',
    element: 'Electric',
    pveTier: 'A',
    sources: [G8, IV],
  },
  {
    slug: 'zhu-yuan',
    name: 'Zhu Yuan',
    role: 'Attack (Main DPS)',
    rarity: 'S-Rank',
    element: 'Ether',
    pveTier: 'A',
    sources: [G8, IV],
  },
  {
    slug: 'asaba-harumasa',
    name: 'Asaba Harumasa',
    aliases: ['Harumasa'],
    role: 'Attack (Main DPS)',
    rarity: 'S-Rank',
    element: 'Electric',
    pveTier: 'A',
    sources: [G8, IV],
  },
];
