import type { ClassRecord } from '@/app/lib/game-hub/types';

// ARC Raiders weapons are the tiered "unit" (looter_shooter blueprint).
//  - role      = weapon type (Battle Rifle, SMG, …)
//  - rarity    = loot rarity (Common → Legendary)
//  - pveTier   = Overall axis = ARC armor-penetration rating (the community
//                ranking axis per the blueprint; Very Weak → Very Strong)
//  - playstyle = the weapon's handling note
// No separate PvP tier exists in the source, so pvpTier is omitted.
const WIKI = 'https://arc-raiders.fandom.com/wiki/Weapons';
const SHIELDS = 'https://arc-raiders.fandom.com/wiki/Shields';

export const WEAPONS: ClassRecord[] = [
  {
    slug: 'aphelion',
    name: 'Aphelion',
    role: 'Battle Rifle',
    rarity: 'Legendary',
    pveTier: 'Strong',
    playstyle: 'Fires high-velocity energy rounds; premium legendary energy option.',
    sources: [WIKI],
  },
  {
    slug: 'anvil',
    name: 'Anvil',
    role: 'Hand Cannon',
    rarity: 'Uncommon',
    pveTier: 'Strong',
    playstyle: 'High damage and headshot damage but slow handling; heavy ammo penetrates armor.',
    sources: [WIKI],
  },
  {
    slug: 'arpeggio',
    name: 'Arpeggio',
    role: 'Burst Rifle',
    rarity: 'Uncommon',
    pveTier: 'Moderate',
    playstyle: 'Decent damage output and accuracy.',
    sources: [WIKI],
  },
  {
    slug: 'bettina',
    name: 'Bettina',
    role: 'Assault Rifle',
    rarity: 'Epic',
    pveTier: 'Strong',
    playstyle: 'Slow fire rate but high damage; heavy ammo makes it strong vs armored ARC.',
    sources: [WIKI],
  },
  {
    slug: 'bobcat',
    name: 'Bobcat',
    role: 'SMG',
    rarity: 'Epic',
    pveTier: 'Very Weak',
    playstyle: 'High fire rate but low accuracy; close-range PvP spray.',
    sources: [WIKI],
  },
  {
    slug: 'burletta',
    name: 'Burletta',
    role: 'Pistol',
    rarity: 'Uncommon',
    pveTier: 'Very Weak',
    playstyle: 'Decent damage and accuracy sidearm.',
    sources: [WIKI],
  },
  {
    slug: 'equalizer',
    name: 'Equalizer',
    role: 'Energy Beam Gun',
    rarity: 'Legendary',
    pveTier: 'Very Strong',
    playstyle: 'High-capacity experimental beam rifle; best-in-class ARC armor penetration.',
    sources: [WIKI],
  },
  {
    slug: 'ferro',
    name: 'Ferro',
    role: 'Break-Action Rifle',
    rarity: 'Common',
    pveTier: 'Strong',
    playstyle:
      'Hits hard but must reload after every shot; popular cheap armor-pen starter (40 base body damage).',
    sources: [WIKI, SHIELDS],
  },
  {
    slug: 'hairpin',
    name: 'Hairpin',
    role: 'Bolt-Action Pistol',
    rarity: 'Common',
    pveTier: 'Very Weak',
    playstyle: 'Built-in silencer; great for stealth but tricky in a firefight.',
    sources: [WIKI],
  },
  {
    slug: 'hullcracker',
    name: 'Hullcracker',
    role: 'Grenade Launcher',
    rarity: 'Epic',
    pveTier: 'Very Strong',
    playstyle: 'Explosive projectiles that only detonate on ARC; anti-machine specialist.',
    sources: [WIKI],
  },
  {
    slug: 'il-toro',
    name: 'IL Toro',
    role: 'Pump-Action Shotgun',
    rarity: 'Uncommon',
    pveTier: 'Weak',
    playstyle: 'Large spread, sharp falloff, high close-range damage.',
    sources: [WIKI],
  },
  {
    slug: 'jupiter',
    name: 'Jupiter',
    role: 'Bolt-Action Sniper Rifle',
    rarity: 'Legendary',
    pveTier: 'Strong',
    playstyle: 'Incredible projectile velocity; can pierce multiple targets in one shot.',
    sources: [WIKI],
  },
  {
    slug: 'kettle',
    name: 'Kettle',
    role: 'Semi-Auto Assault Rifle',
    rarity: 'Common',
    pveTier: 'Very Weak',
    playstyle: 'Quick and accurate but low bullet velocity and slow reload.',
    sources: [WIKI],
  },
  {
    slug: 'osprey',
    name: 'Osprey',
    role: 'Scoped Sniper Rifle',
    rarity: 'Rare',
    pveTier: 'Moderate',
    playstyle: 'Reliable damage and accuracy; accessible mid-tier sniper.',
    sources: [WIKI],
  },
  {
    slug: 'rattler',
    name: 'Rattler',
    role: 'Assault Rifle',
    rarity: 'Common',
    pveTier: 'Moderate',
    playstyle: 'Cheap offensive option; reloads 2 bullets at a time.',
    sources: [WIKI],
  },
  {
    slug: 'renegade',
    name: 'Renegade',
    role: 'Lever-Action Rifle',
    rarity: 'Rare',
    pveTier: 'Moderate',
    playstyle: 'High damage, accuracy and headshot damage.',
    sources: [WIKI],
  },
  {
    slug: 'stitcher',
    name: 'Stitcher',
    role: 'SMG',
    rarity: 'Common',
    pveTier: 'Very Weak',
    playstyle: 'Good damage but low fire rate and hard to control.',
    sources: [WIKI],
  },
  {
    slug: 'tempest',
    name: 'Tempest',
    role: 'Assault Rifle',
    rarity: 'Epic',
    pveTier: 'Moderate',
    playstyle: 'Full-auto AR with moderate fire rate and accuracy; well-rounded PvP rifle.',
    sources: [WIKI],
  },
  {
    slug: 'torrente',
    name: 'Torrente',
    role: 'LMG',
    rarity: 'Rare',
    pveTier: 'Moderate',
    playstyle: 'Large ammo capacity but only accurate while crouched; suppression tool.',
    sources: [WIKI],
  },
  {
    slug: 'venator',
    name: 'Venator',
    role: '2-Shot Pistol',
    rarity: 'Rare',
    pveTier: 'Moderate',
    playstyle: 'Fires two shots at a time.',
    sources: [WIKI],
  },
  {
    slug: 'vulcano',
    name: 'Vulcano',
    role: 'Semi-Auto Shotgun',
    rarity: 'Epic',
    pveTier: 'Weak',
    playstyle: 'Good spread but sharp falloff; aggressive close-range shotgun.',
    sources: [WIKI],
  },
];
